/**
 * LivePreview - Inline preview component for documentation
 * 
 * Features:
 * - Configurable tabs: preview, code, console (in any order)
 * - Tab switching between views
 * - "Try Live" button opens full Monaco editor modal
 * - Auto-height container that grows with content
 * - Uses code-window styling for consistent terminal look
 * - Scoped console output per instance (multiple on same page supported)
 * - Uses client:visible for lazy hydration (runs when scrolled into view)
 * 
 * Usage in SSG (generated by Shiki transformer):
 * ```tsx
 * <LivePreview 
 *     code={base64EncodedCode}
 *     highlightedCode={shikiHtml}
 *     language="tsx"
 *     tabs={['code', 'preview', 'console']}
 *     live={true}
 *     client:visible
 * />
 * ```
 */

import { component, signal, onMounted, onUnmounted, type Define } from 'sigx';
import { runCode, clearPreview, getConsoleLogs, type ExecutionResult, type ConsoleEntry } from '../execution';
import { initAllRuntimes, isRuntimeInitialized } from '../runtime';
import { injectStyles } from '../utils/modal-styles';

// Counter for generating unique container IDs
let instanceCounter = 0;

/** Tab types */
export type TabType = 'preview' | 'code' | 'console';

/** Props for LivePreview component */
export type LivePreviewProps = 
    & Define.Prop<'code', string>            // Base64 encoded source code
    & Define.Prop<'highlightedCode', string> // Pre-highlighted HTML from Shiki
    & Define.Prop<'language', string, false> // Language (default: 'tsx')
    & Define.Prop<'filename', string, false> // Optional filename
    & Define.Prop<'tabs', TabType[], false>  // Tabs to show, in order (default: ['preview', 'code'])
    & Define.Prop<'live', boolean, false>    // Show "Try Live" button
    & Define.Event<'edit', string>;          // Emitted when Edit is clicked

/**
 * Decode base64 string (browser-safe)
 */
function decodeBase64(str: string): string {
    try {
        return decodeURIComponent(escape(atob(str)));
    } catch {
        return atob(str);
    }
}

/**
 * Get language display label
 */
function getLanguageLabel(lang: string): string {
    const labels: Record<string, string> = {
        'tsx': 'TSX',
        'jsx': 'JSX',
        'ts': 'TypeScript',
        'typescript': 'TypeScript',
        'js': 'JavaScript',
        'javascript': 'JavaScript',
    };
    return labels[lang.toLowerCase()] ?? lang.toUpperCase();
}

/**
 * LivePreview - Inline component preview with tabs
 */
export const LivePreview = component<LivePreviewProps>(({ props, emit }) => {
    // Generate unique ID for this instance
    const containerId = `sigx-preview-${++instanceCounter}`;
    
    // Refs for imperative DOM manipulation (avoids re-render issues)
    let loadingRef: HTMLElement | null = null;
    let errorRef: HTMLElement | null = null;
    let consoleRef: HTMLElement | null = null;
    
    // Determine initial tab from tabs array (first tab is selected)
    const tabs = props.tabs ?? ['preview', 'code'] as TabType[];
    const initialTab = tabs[0] ?? 'preview';
    
    // State
    const activeTab = signal<TabType>(initialTab);
    const consoleLogs = signal<ConsoleEntry[]>([]);
    
    // Poll interval for console updates
    let consolePollingInterval: ReturnType<typeof setInterval> | null = null;
    
    // Decode the source code from base64
    const getSourceCode = () => {
        try {
            return decodeBase64(props.code ?? '');
        } catch {
            return props.code ?? '';
        }
    };
    
    // Helper to show/hide loading imperatively (no re-render)
    function setLoading(loading: boolean) {
        if (loadingRef) loadingRef.style.display = loading ? 'flex' : 'none';
    }
    
    // Helper to show error imperatively (no re-render)
    function setError(message: string | null) {
        if (errorRef) {
            errorRef.style.display = message ? 'flex' : 'none';
            const textEl = errorRef.querySelector('.code-window-error-text');
            if (textEl) textEl.textContent = message ?? '';
        }
    }
    
    // Run code on mount
    onMounted(async () => {
        // Ensure runtime is initialized
        if (!isRuntimeInitialized()) {
            await initAllRuntimes();
        }
        
        // Auto-execute to show preview
        await executePreview();
        
        // Start polling for console updates (effects may log after initial execution)
        // Poll every 100ms to catch logs from effects, click handlers, etc.
        consolePollingInterval = setInterval(() => {
            const currentLogs = getConsoleLogs(containerId);
            if (currentLogs.length !== consoleLogs.length) {
                consoleLogs.$set(currentLogs.slice()); // Copy to trigger reactivity
            }
        }, 100);
    });
    
    // Cleanup on unmount
    onUnmounted(() => {
        // Stop console polling
        if (consolePollingInterval) {
            clearInterval(consolePollingInterval);
            consolePollingInterval = null;
        }
        
        const container = document.getElementById(containerId);
        clearPreview(container);
    });
    
    // Track if we're currently running (not reactive)
    let isRunning = false;
    
    /** Execute the code and render preview */
    async function executePreview() {
        if (isRunning) return;
        
        isRunning = true;
        setLoading(true);
        setError(null);
        
        // Wait for DOM to be ready
        await new Promise(resolve => requestAnimationFrame(resolve));
        
        try {
            const sourceCode = getSourceCode();
            
            // Execute code - the runtime injection scopes #sandbox to our container
            const result = await runCode(sourceCode, containerId);
            
            if (!result.success && result.error) {
                setError(result.error);
            }
            
            // Update console logs after execution (scoped to this containerId)
            consoleLogs.$set(getConsoleLogs(containerId));
        } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            setError(message);
            console.error('[LivePreview] Exception:', err);
        } finally {
            isRunning = false;
            setLoading(false);
        }
    }
    
    /** Get console icon based on log type */
    function getConsoleIcon(type: string): string {
        switch (type) {
            case 'error': return '✕';
            case 'warn': return '⚠';
            case 'info': return 'ℹ';
            default: return '›';
        }
    }
    
    /** Open the full editor modal */
    function handleEdit() {
        const sourceCode = getSourceCode();
        
        // Inject modal styles first
        injectStyles();
        
        // Import and open the modal dynamically
        import('./LiveCodeModal').then(({ LiveCodeModal }) => {
            import('sigx').then(({ render }) => {
                // Create modal container
                const modalRoot = document.createElement('div');
                modalRoot.id = `playground-modal-root-${Date.now()}`;
                document.body.appendChild(modalRoot);
                
                // Close handler
                const handleClose = () => {
                    render(null as any, modalRoot);
                    modalRoot.remove();
                    // Re-execute in case code changed
                    executePreview();
                };
                
                // Render modal
                render(
                    <LiveCodeModal 
                        code={sourceCode} 
                        language={props.language ?? 'tsx'} 
                        filename={props.filename ?? ''} 
                        onClose={handleClose} 
                    />, 
                    modalRoot
                );
            });
        });
        
        emit('edit', sourceCode);
    }
    
    /** Switch to a tab */
    function switchTab(tab: TabType) {
        activeTab.value = tab;
    }
    
    return () => {
        const lang = props.language ?? 'tsx';
        const filename = props.filename;
        const tabsToShow = props.tabs ?? ['preview', 'code'] as TabType[];
        const showLiveButton = props.live ?? false;
        const currentTab = activeTab.value;
        
        return (
            <div class="code-window code-window-live code-window-preview">
                {/* Header - Terminal style with dots, tabs, and edit button */}
                <div class="code-window-header">
                    <div class="code-window-header-left">
                        <div class="code-window-dots">
                            <span class="code-window-dot dot-red" />
                            <span class="code-window-dot dot-yellow" />
                            <span class="code-window-dot dot-green" />
                        </div>
                        {filename 
                            ? <span class="code-window-filename">{filename}</span>
                            : <span class="code-window-lang">{getLanguageLabel(lang)}</span>
                        }
                    </div>
                    
                    {/* Tabs - rendered in order from tabs prop */}
                    <div class="code-window-tabs">
                        {tabsToShow.map(tab => (
                            <button 
                                class={`code-window-tab ${currentTab === tab ? 'code-window-tab-active' : ''}`}
                                onClick={() => switchTab(tab)}
                            >
                                {tab.charAt(0).toUpperCase() + tab.slice(1)}
                                {tab === 'console' && consoleLogs.length > 0 && (
                                    <span class="code-window-tab-badge">{consoleLogs.length}</span>
                                )}
                            </button>
                        ))}
                    </div>
                    
                    {/* Try Live button - only shown when live prop is true */}
                    {showLiveButton && (
                        <button 
                            class="code-window-try-live"
                            onClick={handleEdit}
                            title="Open in Live Playground"
                        >
                            ⚡ Try Live
                        </button>
                    )}
                </div>
                
                {/* Preview Pane */}
                {tabsToShow.includes('preview') && (
                    <div 
                        class="code-window-preview-pane"
                        style={{ display: currentTab === 'preview' ? 'block' : 'none' }}
                    >
                        {/* Error Display - controlled imperatively via setError() */}
                        <div 
                            class="code-window-error" 
                            style={{ display: 'none' }}
                            ref={(el: HTMLElement) => { if (el) errorRef = el; }}
                        >
                            <span class="code-window-error-icon">⚠️</span>
                            <pre class="code-window-error-text"></pre>
                        </div>
                        
                        {/* Loading State - controlled imperatively via setLoading() */}
                        <div 
                            class="code-window-preview-loading" 
                            style={{ display: 'none' }}
                            ref={(el: HTMLElement) => { if (el) loadingRef = el; }}
                        >
                            <span class="code-window-spinner" />
                            Loading preview...
                        </div>
                        
                        {/* Preview Container - code will mount into this element */}
                        <div 
                            id={containerId}
                            class="code-window-preview-container"
                        />
                    </div>
                )}
                
                {/* Console Pane */}
                {tabsToShow.includes('console') && (
                    <div 
                        class="code-window-console-pane"
                        style={{ display: currentTab === 'console' ? 'block' : 'none' }}
                        ref={(el: HTMLElement) => { if (el) consoleRef = el; }}
                    >
                        {consoleLogs.length === 0 ? (
                            <div class="code-window-console-empty">No console output</div>
                        ) : (
                            consoleLogs.map((log: ConsoleEntry) => (
                                <div class={`code-window-console-line code-window-console-${log.type}`}>
                                    <span class="code-window-console-icon">{getConsoleIcon(log.type)}</span>
                                    <span class="code-window-console-text">{log.args.join(' ')}</span>
                                </div>
                            ))
                        )}
                    </div>
                )}
                
                {/* Code Pane */}
                {tabsToShow.includes('code') && (
                    <div 
                        class="code-window-content"
                        style={{ display: currentTab === 'code' ? 'block' : 'none' }}
                        ref={(el: HTMLElement) => {
                            if (el && props.highlightedCode) {
                                el.innerHTML = props.highlightedCode;
                            }
                        }}
                    />
                )}
            </div>
        );
    };
}, { name: 'LivePreview' }); // Important: name for island registration

